on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate zip file
        id: build-image
        run: |
          sudo apt-get update
          sudo apt-get install zip unzip
          zip -r hitmakers_radar.zip . -x "data/*" "node_modules/*" "build/*" ".git/*"
